### ISSUE TITLE
mc_server_group_extend throws error if device is added with a dns name instead of ipaddress

### ISSUE THREAD

**Issue by onkelbeh** [vigonotion/aiomusiccast#21]
Hi again,

first a big thanks for your help, brought me closer to a solution, and thank you for your work on this wonderful integration.
I have four Yamaha RXV-679, running HA 2021.8.3 with aiomusiccast-0.9.1,
I am still trying to get the formerly working group functionality (with mini-media-player) back again.

Current release of mini-media-player cannot use media_player's join, so I had to build it from the current dev tree at commit [a3a4a69](https://github.com/kalkih/mini-media-player/tree/a3a4a6931c6811a942ea38c653ab5bb6bf188ca8).

However, I had added the Yamaha's with their dns name in config flow.
When I try to join a mc client, the master stops playing for a second or two, and HA tells:
```
2021-09-06 19:50:27 WARNING (MainThread) [aiomusiccast.musiccast_device] Coordinator of 172.16.2.131 did not receive the expected group data update via UDP. Fetching manually.
2021-09-06 19:50:28 WARNING (MainThread) [aiomusiccast.musiccast_device] Coordinator of 172.16.2.131 did not receive the expected group data update via UDP. Fetching manually.
2021-09-06 19:50:28 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139976403338480] 172.16.2.131: Failed to extent group by clients ['rxv679-wohnen.in.edevau.net']
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/lib/python3.9/site-packages/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/lib/python3.9/site-packages/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/lib/python3.9/site-packages/homeassistant/components/yamaha_musiccast/media_player.py", line 756, in async_join_players
    await self.coordinator.musiccast.mc_server_group_extend(
  File "/usr/lib/python3.9/site-packages/aiomusiccast/musiccast_device.py", line 831, in mc_server_group_extend
    await self.mc_server_group_extend(zone, client_ips, group_id, distribution_num, False)
  File "/usr/lib/python3.9/site-packages/aiomusiccast/musiccast_device.py", line 833, in mc_server_group_extend
    raise MusicCastGroupException(
aiomusiccast.exceptions.MusicCastGroupException: 172.16.2.131: Failed to extent group by clients ['rxv679-wohnen.in.edevau.net']
```

When I set up the Yamaha's int the config flow with their IP adresses instead of their hostname, it seems to work, HA only says in the log:
```
2021-09-06 19:53:10 WARNING (MainThread) [aiomusiccast.musiccast_device] Coordinator of 172.16.2.131 did not receive the expected group data update via UDP. Fetching manually.
```

DNS is set up properly, HA is able to resolve in both directions:
```bash
root@g18-hass:/etc/homeassistant/www # host rxv679-wohnen.in.edevau.net
rxv679-wohnen.in.edevau.net has address 172.16.2.136
root@g18-hass:/etc/homeassistant/www # host 172.16.2.136
136.2.16.172.in-addr.arpa domain name pointer rxv679-wohnen.in.edevau.net.
root@g18-hass:/etc/homeassistant/www # host rxv679-werkstatt.in.edevau.net
rxv679-werkstatt.in.edevau.net has address 172.16.2.131
root@g18-hass:/etc/homeassistant/www # host 172.16.2.131
131.2.16.172.in-addr.arpa domain name pointer rxv679-werkstatt.in.edevau.net.
```
The HA host is not on the same VLAN with the Yamahas (different building), all affected Yamahas share the same network, UDP traffic is allowed.

Would you say the it is better practice to use ip adresses instead of the host names?
Should I worry about the UDP message?

Thanks for your help.

**Comment by micha91** [comment]
For the time being, we only support the IP addresses for the grouping functionality, because the Yamaha devices expect an IP address provided, when we try to extend the group member list. As most users use the device discovery to add their devices, we are able to update the IP address of the device by using the serial number as single source of truth. However, we will take a look into that and see, whether it's possible to support hostnames.
Regarding your UDP problem when you use the IP address, I believe this could be related to the delays your network infrastructure leads to. We are using UDP messages to let the device tell us when something changes. And the device only sends us information about the kind of change so that we can then pull the correct information from the device. In case of grouping we have to send multiple requests and we have to wait until the device tells us that it is ready has processed the previous one. So there is some kind of structure like this:
1. HA HTTP -add group member-> Yamaha
2. HA <-updated group members- UDP Yamaha
3. HA HTTP -get group members-> Yamaha
4. HA HTTP -start distribution-> Yamaha

If we do not get the expected status information within one second, we log this message and send a request to the device. So it is like we skip step 2 from above and hope that the device is already ready. If it isn't, we try to repeat the whole process an additional time and if that fails we raise an exception (just like you had it when you were using the host names).
But maybe you have problems with the UDP connection in general. If you for example play some net-usb sources, do you get correct artist/title meta information displayed in real time in the media-control (or mini-media-player) card?

**Comment by onkelbeh** [comment]
Thanks for this great and compehensible explanation. I can live with that for now, I just have to use fixed IP's for them now, no big thing. Otherwise I also have to use the DNS names for them, HA's web frontend is used via SSL (ha-proxy), and, to embed the Yamaha's web interface in the gui (for newer browsers), I have to pass their traffic also through ha-proxy, ha-proxy (currently) uses the hostname to pick the correct Amp as a backend/server.

I do not believe it could be caused by delay. Total RRT is < 3ms.

Often (not always) I see that meta informations is not updated on the Yamahas, at the beginning of a playlist, the title is displayed properly, but the following titles aren't updated, neither on the Yamahas, nor in the miniplayer. The information diplayed on the mini-player matches the Amps display, even if it's not correct.

Can you explain from where the Yamaha's and the mini players display information is taken from?

This would help to explore the apparent network issue a bit further. I have wireshark on the HA box, but currently I cannot monitor the traffic between the NAS an the Yamahas.

I'll try to set up a port mirroring for the remote Yamahas to prove your UDP packet loss theory. I did put the local Yamaha in a routed VLAN, now it has the same display-not-updated-on-song-change issue, if I can't fix it, I'll try to build a L2 VLAN for the remote Yamahas to try it without routing.

**Comment by micha91** [comment]
The UDP channel is the only communication channel the MusicCast device can use to send data to HA on its own. As we did not want to pull all information every second from every single device, we decided to only update the data when the device tells us, that there is a relevant change. In addition, we pull all information from every device once a minute. This way we ensure that the data are not inconsistent forever if a UDP package got lost.
If you say that information like the title are not up to date, it could also be caused by the loss of UDP packages. Without them, HA only updates information once a minute. We could discuss, whether we want to add a configuration flag in HA to define that the data should be pulled every x seconds. It's not really clean and would cause much more traffic, but it's the only way, I see, to keep data up to date, if UDP packages cannot be transmitted.
